name: Appliance installer
on:
  push:
  workflow_dispatch:
jobs:
  apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./vbox.sh install
      - run: ./minio.sh install-server
  docker:  
    runs-on: ubuntu-latest
    steps:
      - run: |
        ./docker.sh install-desktop;
        docker ps
      - run: |
        ./docker.sh install;
        docker ps
      
