name: Appliance installer
on:
  push:
  workflow_dispatch:
defaults:
  run:
    working-directory: apps
jobs:
  apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: ./vbox.sh install
      - run: ./minio.sh install-server
  docker:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          ./docker.sh install
          docker ps
          
      
