name: database

on: [push, workflow_dispatch]
  
defaults:
  run:
    working-directory: database
jobs:
  mysql:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04 ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: ./mysql.sh purge
      - run: ./mysql.sh install insecure
      - run: ./mysql.sh start
      - run: ./mysql.sh setRootPassword password --init
