name: database

on: workflow_dispatch
defaults:
  run:
    working-directory: database
jobs:
  # This workflow contains a single job called "build"
  mysql:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: ./mysql.sh purge
      - run: ./mysql.sh install insecure
      - run: ./mysql.sh start
      - run: ./mysql.sh setRootPassword password --init
