name: database

on: 
  schedule:
     - cron:  '0 0 * * 1'
  workflow_dispatch:
  
defaults:
  run:
    working-directory: database
jobs:
  mysql:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - run: ./mysql.sh purge
      - run: ./mysql.sh install insecure
      - run: ./mysql.sh start
      - run: ./mysql.sh set-root-password password --init
