
name: database

on: push
defaults:
      run:
        working-directory: database
jobs:
  # This workflow contains a single job called "build"
  mysql:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: ./mysql.sh setup
      - run: sudo cat /etc/mysql/debian.cnf
      - run: mysql --protocol=tcp -h 127.0.0.1 -uroot -ppassword
      - run: ./mysql.sh setRootPassword password --init
      
      
